name: Publish to NPM
on: 
  push:
    tags:
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "ref: ${{ github.ref }}"
          echo "event_name: ${{ github.event_name }}"
          echo "toJson(event): ${{ toJson(github.event) }}"
      - if: startsWith(github.ref, 'refs/tags/')
        run: echo "On a tag"

